/*
 screenfull
 v5.0.0 - 2019-09-09
 (c) Sindre Sorhus; MIT License
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},d="undefined"!==typeof module&&module.exports,e=function(){for(var b,e=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],c=0,f=e.length,d={};c<f;c++)if((b=e[c])&&b[1]in a){for(c=0;c<b.length;c++)d[e[0][c]]=b[c];return d}return!1}(),b={change:e.fullscreenchange,error:e.fullscreenerror},c={request:function(b){return new Promise(function(c,d){var f=function(){this.off("change",
f);c()}.bind(this);this.on("change",f);b=b||a.documentElement;Promise.resolve(b[e.requestFullscreen]())["catch"](d)}.bind(this))},exit:function(){return new Promise(function(b,c){if(this.isFullscreen){var d=function(){this.off("change",d);b()}.bind(this);this.on("change",d);Promise.resolve(a[e.exitFullscreen]())["catch"](c)}else b()}.bind(this))},toggle:function(a){return this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},
on:function(c,e){var d=b[c];d&&a.addEventListener(d,e,!1)},off:function(c,e){var d=b[c];d&&a.removeEventListener(d,e,!1)},raw:e};e?(Object.defineProperties(c,{isFullscreen:{get:function(){return!!a[e.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[e.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[e.fullscreenEnabled]}}}),d?module.exports=c:window.screenfull=c):d?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function d(a,c){var e=-1,d=a?a.length:0;if("number"==typeof d&&-1<d&&d<=p)for(;++e<d;)c(a[e],e,a);else b(a,c)}function e(b){b=String(b).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(b)?b:a(b)}function b(a,b){for(var c in a)n.call(a,c)&&b(a[c],c,a)}function c(b){return null==b?a(b):D.call(b).slice(8,-1)}function h(a,b){var c=null!=a?typeof a[b]:"number";return!/^(?:boolean|number|string|undefined)$/.test(c)&&
("object"==c?!!a[b]:!0)}function g(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function k(a,b){var c=null;d(a,function(e,d){c=b(c,e,d,a)});return c}function f(a){function d(b){return k(b,function(b,c){var d=c.pattern||g(c);!b&&(b=RegExp("\\b"+d+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+d+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+d+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((b=String(c.label&&!RegExp(d,"i").test(c.label)?c.label:b).split("/"))[1]&&!/[\d.]+/.test(b[0])&&(b[0]+=
" "+b[1]),c=c.label||c,b=e(b[0].replace(RegExp(d,"i"),c).replace(RegExp("; *(?:"+c+"[_-])?","i")," ").replace(RegExp("("+c+")[-_.]?(\\w)","i"),"$1 $2")));return b})}function m(b){return k(b,function(b,c){return b||(RegExp(c+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var n=r,p=a&&"object"==typeof a&&"String"!=c(a);p&&(n=a,a=null);var t=n.navigator||{},q=t.userAgent||"";a||(a=q);var E=p?!!t.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(D.toString()),
y=p?"Object":"ScriptBridgingProxyObject",M=p?"Object":"Environment",L=p&&n.java?"JavaPackage":c(n.java),V=p?"Object":"RuntimeObject";M=(L=/\bJava/.test(L)&&n.java)&&c(n.environment)==M;var W=L?"a":"\u03b1",X=L?"b":"\u03b2",S=n.document||{},H=n.operamini||n.opera,O=v.test(O=p&&H?H["[[Class]]"]:c(H))?O:H=null,l,P=a;p=[];var Q=null,I=a==q;q=I&&H&&"function"==typeof H.version&&H.version();var A=function(b){return k(b,function(b,c){return b||RegExp("\\b"+(c.pattern||g(c))+"\\b","i").exec(a)&&(c.label||
c)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),u=function(b){return k(b,function(b,c){return b||RegExp("\\b"+(c.pattern||g(c))+"\\b","i").exec(a)&&(c.label||c)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),B=d([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),G=function(b){return k(b,function(b,c,d){return b||(c[B]||c[/^[a-z]+(?: +[a-z]+\b)*/i.exec(B)]||RegExp("\\b"+g(d)+"(?:\\b|\\w*\\d)","i").exec(a))&&d})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),w=function(b){return k(b,function(b,c){var d=c.pattern||g(c);if(!b&&(b=RegExp("\\b"+d+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var f=b,n=c.label||c,m={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};d&&n&&/^Win/i.test(f)&&!/^Windows Phone /i.test(f)&&(m=m[/[\d.]+$/.exec(f)])&&(f="Windows "+m);f=String(f);d&&n&&(f=f.replace(RegExp(d,"i"),n));b=f=e(f.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return b})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);A&&(A=[A]);G&&!B&&(B=d([G]));if(l=/\bGoogle TV\b/.exec(B))B=l[0];/\bSimulator\b/i.test(a)&&(B=(B?B+" ":"")+"Simulator");"Opera Mini"==u&&/\bOPiOS\b/.test(a)&&p.push("running in Turbo/Uncompressed mode");"IE"==u&&/\blike iPhone OS\b/.test(a)?(l=f(a.replace(/like iPhone OS/,"")),G=l.manufacturer,B=l.product):/^iP/.test(B)?(u||(u="Safari"),w="iOS"+((l=/ OS ([\d_]+)/i.exec(a))?" "+l[1].replace(/_/g,"."):"")):"Konqueror"!=u||/buntu/i.test(w)?G&&"Google"!=G&&(/Chrome/.test(u)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(B))||/\bAndroid\b/.test(w)&&/^Chrome/.test(u)&&/\bVersion\//i.test(a)?(u="Android Browser",w=/\bAndroid\b/.test(w)?w:"Android"):"Silk"==u?(/\bMobi/i.test(a)||(w="Android",p.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&p.unshift("accelerated")):"PaleMoon"==u&&(l=/\bFirefox\/([\d.]+)\b/.exec(a))?p.push("identifying as Firefox "+l[1]):"Firefox"==u&&(l=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(w||(w="Firefox OS"),B||(B=l[1])):!u||(l=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(u))?(u&&!B&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(l+"/")+8))&&(u=null),(l=B||G||w)&&(B||G||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(w))&&(u=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(w)?w:l)+" Browser")):"Electron"==u&&(l=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&p.push("Chromium "+l):w="Kubuntu";q||(q=m(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",g(u),"(?:Firefox|Minefield|NetFront)"]));
if(l="iCab"==A&&3<parseFloat(q)&&"WebKit"||/\bOpera\b/.test(u)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(A)&&"WebKit"||!A&&/\bMSIE\b/i.test(a)&&("Mac OS"==w?"Tasman":"Trident")||"WebKit"==A&&/\bPlayStation\b(?! Vita\b)/i.test(u)&&"NetFront")A=[l];"IE"==u&&(l=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(u+=" Mobile",w="Windows Phone "+(/\+$/.test(l)?l:l+".x"),p.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(u="IE Mobile",w="Windows Phone 8.x",
p.unshift("desktop mode"),q||(q=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=u&&"Trident"==A&&(l=/\brv:([\d.]+)/.exec(a))&&(u&&p.push("identifying as "+u+(q?" "+q:"")),u="IE",q=l[1]);if(I){if(h(n,"global"))if(L&&(l=L.lang.System,P=l.getProperty("os.arch"),w=w||l.getProperty("os.name")+" "+l.getProperty("os.version")),M){try{q=n.require("ringo/engine").version.join("."),u="RingoJS"}catch(U){(l=n.system)&&l.global.system==n.system&&(u="Narwhal",w||(w=l[0].os||null))}u||(u="Rhino")}else"object"==typeof n.process&&
!n.process.browser&&(l=n.process)&&("object"==typeof l.versions&&("string"==typeof l.versions.electron?(p.push("Node "+l.versions.node),u="Electron",q=l.versions.electron):"string"==typeof l.versions.nw&&(p.push("Chromium "+q,"Node "+l.versions.node),u="NW.js",q=l.versions.nw)),u||(u="Node.js",P=l.arch,w=l.platform,q=(q=/[\d.]+/.exec(l.version))?q[0]:null));else c(l=n.runtime)==y?(u="Adobe AIR",w=l.flash.system.Capabilities.os):c(l=n.phantom)==V?(u="PhantomJS",q=(l=l.version||null)&&l.major+"."+l.minor+
"."+l.patch):"number"==typeof S.documentMode&&(l=/\bTrident\/(\d+)/i.exec(a))?(q=[q,S.documentMode],(l=+l[1]+4)!=q[1]&&(p.push("IE "+q[1]+" mode"),A&&(A[1]=""),q[1]=l),q="IE"==u?String(q[1].toFixed(1)):q[0]):"number"==typeof S.documentMode&&/^(?:Chrome|Firefox)\b/.test(u)&&(p.push("masking as "+u+" "+q),u="IE",q="11.0",A=["Trident"],w="Windows");w=w&&e(w)}q&&(l=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(q)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(I&&t.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(Q=/b/i.test(l)?"beta":"alpha",q=q.replace(RegExp(l+"\\+?$"),"")+("beta"==Q?X:W)+(/\d+\+?/.exec(l)||""));if("Fennec"==u||"Firefox"==u&&/\b(?:Android|Firefox OS)\b/.test(w))u="Firefox Mobile";else if("Maxthon"==u&&q)q=q.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(B))"Xbox 360"==B&&(w=null),"Xbox 360"==B&&/\bIEMobile\b/.test(a)&&p.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(u)&&(!u||B||/Browser|Mobi/.test(u))||"Windows CE"!=w&&!/Mobi/i.test(a))if("IE"==u&&I)try{null===n.external&&
p.unshift("platform preview")}catch(U){p.unshift("embedded")}else(/\bBlackBerry\b/.test(B)||/\bBB10\b/.test(a))&&(l=(RegExp(B.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||q)?(l=[l,/BB10/.test(a)],w=(l[1]?(B=null,G="BlackBerry"):"Device Software")+" "+l[0],q=null):this!=b&&"Wii"!=B&&(I&&H||/Opera/.test(u)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==u&&/\bOS X (?:\d+\.){2,}/.test(w)||"IE"==u&&(w&&!/^Win/.test(w)&&5.5<q||/\bWindows XP\b/.test(w)&&8<q||8==q&&!/\bTrident\b/.test(a)))&&!v.test(l=
f.call(b,a.replace(v,"")+";"))&&l.name&&(l="ing as "+l.name+((l=l.version)?" "+l:""),v.test(u)?(/\bIE\b/.test(l)&&"Mac OS"==w&&(w=null),l="identify"+l):(l="mask"+l,u=O?e(O.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(l)&&(w=null),I||(q=null)),A=["Presto"],p.push(l));else u+=" Mobile";if(l=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){l=[parseFloat(l.replace(/\.(\d)$/,".0$1")),l];if("Safari"==u&&"+"==l[1].slice(-1))u="WebKit Nightly",Q="alpha",q=l[1].slice(0,-1);else if(q==l[1]||q==(l[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))q=null;l[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==l[0]&&537.36==l[2]&&28<=parseFloat(l[1])&&"WebKit"==A&&(A=["Blink"]);I&&(E||l[1])?(A&&(A[1]="like Chrome"),l=l[1]||(l=l[0],530>l?1:532>l?2:532.05>l?3:533>l?4:534.03>l?5:534.07>l?6:534.1>l?7:534.13>l?8:534.16>l?9:534.24>l?10:534.3>l?11:535.01>l?12:535.02>l?"13+":535.07>l?15:535.11>l?16:535.19>l?17:536.05>l?18:536.1>l?19:537.01>l?20:537.11>l?"21+":537.13>l?23:537.18>l?24:537.24>l?25:537.36>l?26:"Blink"!=
A?"27":"28")):(A&&(A[1]="like Safari"),l=(l=l[0],400>l?1:500>l?2:526>l?3:533>l?4:534>l?"4+":535>l?5:537>l?6:538>l?7:601>l?8:"8"));A&&(A[1]+=" "+(l+="number"==typeof l?".x":/[.+]/.test(l)?"":"+"));"Safari"==u&&(!q||45<parseInt(q))&&(q=l)}"Opera"==u&&(l=/\bzbov|zvav$/.exec(w))?(u+=" ",p.unshift("desktop mode"),"zvav"==l?(u+="Mini",q=null):u+="Mobile",w=w.replace(RegExp(" *"+l+"$"),"")):"Safari"==u&&/\bChrome\b/.exec(A&&A[1])&&(p.unshift("desktop mode"),u="Chrome Mobile",q=null,/\bOS X\b/.test(w)?(G=
"Apple",w="iOS 4.3+"):w=null);q&&0==q.indexOf(l=/[\d.]+$/.exec(w))&&-1<a.indexOf("/"+l+"-")&&(w=String(w.replace(l,"")).replace(/^ +| +$/g,""));A&&!/\b(?:Avant|Nook)\b/.test(u)&&(/Browser|Lunascape|Maxthon/.test(u)||"Safari"!=u&&/^iOS/.test(w)&&/\bSafari\b/.test(A[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(u)&&A[1])&&(l=A[A.length-1])&&p.push(l);p.length&&(p=["("+p.join("; ")+")"]);G&&B&&0>B.indexOf(G)&&p.push("on "+G);B&&p.push((/^on /.test(p[p.length-
1])?"":"on ")+B);if(w){var T=(l=/ ([\d.+]+)$/.exec(w))&&"/"==w.charAt(w.length-l[0].length-1);w={architecture:32,family:l&&!T?w.replace(l[0],""):w,version:l?l[1]:null,toString:function(){var a=this.version;return this.family+(a&&!T?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(l=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(P))&&!/\bi686\b/i.test(P)?(w&&(w.architecture=64,w.family=w.family.replace(RegExp(" *"+l),"")),u&&(/\bWOW64\b/i.test(a)||I&&/\w(?:86|32)$/.test(t.cpuClass||t.platform)&&!/\bWin64; x64\b/i.test(a))&&
p.unshift("32-bit")):w&&/^OS X/.test(w.family)&&"Chrome"==u&&39<=parseFloat(q)&&(w.architecture=64);a||(a=null);n={};n.description=a;n.layout=A&&A[0];n.manufacturer=G;n.name=u;n.prerelease=Q;n.product=B;n.ua=a;n.version=u&&q;n.os=w||{architecture:null,family:null,version:null,toString:function(){return"null"}};n.parse=f;n.toString=function(){return this.description||""};n.version&&p.unshift(q);n.name&&p.unshift(u);w&&u&&(w!=String(w).split(" ")[0]||w!=u.split(" ")[0]&&!B)&&p.push(B?"("+w+")":"on "+
w);p.length&&(n.description=p.join(" "));return n}var m={"function":!0,object:!0},r=m[typeof window]&&window||this,q=m[typeof exports]&&exports;m=m[typeof module]&&module&&!module.nodeType&&module;var t=q&&m&&"object"==typeof global&&global;!t||t.global!==t&&t.window!==t&&t.self!==t||(r=t);var p=Math.pow(2,53)-1,v=/\bOpera/;t=Object.prototype;var n=t.hasOwnProperty,D=t.toString,y=f();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(r.platform=y,define(function(){return y})):q&&
m?b(y,function(a,b){q[b]=a}):r.platform=y}).call(this);var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler();s_oGame&&s_oGame.showPausePanel(!1);s_oMain.startUpdate();sizeHandler()});$(window).blur(function(){s_oGame&&s_oGame.showPausePanel(!0);s_oMain.stopUpdate()});$(window).focus(function(){s_oGame&&s_oGame.showPausePanel(!1);s_oMain.startUpdate()});function trace(a){console.log(a)}
function getSize(a){var d=a.toLowerCase(),e=window.document,b=e.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var c=e.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var h=e.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+d+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";c.appendChild(h);b.insertBefore(c,e.head);
a=7==h["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(c)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a="safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,a);var e=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),b=Math.round(CANVAS_WIDTH*e);e=Math.round(CANVAS_HEIGHT*e);if(e<a){var c=a-e;e+=c;b+=CANVAS_WIDTH/CANVAS_HEIGHT*c}else b<d&&(c=d-b,b+=c,e+=CANVAS_HEIGHT/CANVAS_WIDTH*c);c=a/2-e/2;var h=d/2-b/2,g=CANVAS_WIDTH/b;if(h*g<-EDGEBOARD_X||c*g<-EDGEBOARD_Y)e=Math.min(a/(CANVAS_HEIGHT-
2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=Math.round(CANVAS_WIDTH*e),e=Math.round(CANVAS_HEIGHT*e),c=(a-e)/2,h=(d-b)/2,g=CANVAS_WIDTH/b;s_iOffsetX=-1*h*g;s_iOffsetY=-1*c*g;0<=c&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*b,s_oStage.canvas.height=2*e,canvas.style.width=b+"px",canvas.style.height=
e+"px",s_iScaleFactor=2*Math.min(b/CANVAS_WIDTH,e/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor):s_bMobile||isChrome()?($("#canvas").css("width",b+"px"),$("#canvas").css("height",e+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=e,s_iScaleFactor=Math.min(b/CANVAS_WIDTH,e/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>c||(c=(a-e)/2);$("#canvas").css("top",c+"px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function _checkOrientation(a,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function playSound(a,d,e){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(d),s_aSounds[a].loop(e),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(d)}
function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(d)}function fadeSound(a,d,e,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].fade(d,e,b)}function soundPlaying(a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)return s_aSounds[a].playing()}function createBitmap(a,d,e){var b=new createjs.Bitmap(a),c=new createjs.Shape;d&&e?c.graphics.beginFill("#fff").drawRect(0,0,d,e):c.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=c;return b}
function createSprite(a,d,e,b,c,h){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-e,-b,c,h);a.hitArea=d;return a}function randomFloatBetween(a,d,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(e))}function rotateVector2D(a,d){var e=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),b=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(e,b)}function tweenVectorsOnX(a,d,e){return a+e*(d-a)}
function shuffle(a){for(var d=a.length,e,b;0!==d;)b=Math.floor(Math.random()*d),--d,e=a[d],a[d]=a[b],a[b]=e;return a}function bubbleSort(a){do{var d=!1;for(var e=0;e<a.length-1;e++)a[e]>a[e+1]&&(d=a[e],a[e]=a[e+1],a[e+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}function easeLinear(a,d,e,b){return e*a/b+d}function easeInQuad(a,d,e,b){return e*(a/=b)*a+d}function easeInSine(a,d,e,b){return-e*Math.cos(a/b*(Math.PI/2))+e+d}
function easeInCubic(a,d,e,b){return e*(a/=b)*a*a+d}function getTrajectoryPoint(a,d){var e=new createjs.Point,b=(1-a)*(1-a),c=a*a;e.x=b*d.start.x+2*(1-a)*a*d.traj.x+c*d.end.x;e.y=b*d.start.y+2*(1-a)*a*d.traj.y+c*d.end.y;return e}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=Math.floor(a-60*d);var e="";e=10>d?e+("0"+d+":"):e+(d+":");return 10>a?e+("0"+a):e+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,d){var e=getBounds(a,.9);var b=getBounds(d,.98);return calculateIntersection(e,b)}function calculateIntersection(a,d){var e,b,c,h;var g=a.x+(e=a.width/2);var k=a.y+(b=a.height/2);var f=d.x+(c=d.width/2);var m=d.y+(h=d.height/2);g=Math.abs(g-f)-(e+c);k=Math.abs(k-m)-(b+h);return 0>g&&0>k?(g=Math.min(Math.min(a.width,d.width),-g),k=Math.min(Math.min(a.height,d.height),-k),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:g,height:k,rect1:a,rect2:d}):null}
function dlx_cover(a){a.right.left=a.left;a.left.right=a.right;for(var d=a.down;d!==a;d=d.down)for(var e=d.right;e!==d;e=e.right)e.down.up=e.up,e.up.down=e.down,e.column.size--}function dlx_uncover(a){for(var d=a.up;d!==a;d=d.up)for(var e=d.left;e!==d;e=e.left)e.column.size++,e.down.up=e,e.up.down=e;a.right.left=a;a.left.right=a}
function dlx_search(a,d,e,b,c){if(a.right===a)return b.push(d.slice(0)),b.length>=c?b:null;for(var h=null,g=99999,k=a.right;k!==a;k=k.right){if(0===k.size)return null;k.size<g&&(g=k.size,h=k)}dlx_cover(h);for(var f=h.down;f!==h;f=f.down){d[e]=f.row;for(k=f.right;k!==f;k=k.right)dlx_cover(k.column);g=dlx_search(a,d,e+1,b,c);if(null!==g)return g;for(k=f.left;k!==f;k=k.left)dlx_uncover(k.column)}dlx_uncover(h);return null}
function dlx_solve(a,d,e){for(var b=Array(a[0].length),c=0;c<b.length;c++)b[c]={};for(c=0;c<b.length;c++)b[c].index=c,b[c].up=b[c],b[c].down=b[c],c>=d?(c-1>=d&&(b[c].left=b[c-1]),c+1<b.length&&(b[c].right=b[c+1])):(b[c].left=b[c],b[c].right=b[c]),b[c].size=0;for(c=0;c<a.length;c++)for(var h=null,g=0;g<a[c].length;g++)if(a[c][g]){var k={};k.row=c;k.column=b[g];k.up=b[g].up;k.down=b[g];h?(k.left=h,k.right=h.right,h.right.left=k,h.right=k):(k.left=k,k.right=k);b[g].up.down=k;b[g].up=k;b[g].size++;h=
k}a={};a.right=b[d];a.left=b[b.length-1];b[d].left=a;b[b.length-1].right=a;solutions=[];dlx_search(a,[],0,solutions,e);return solutions}
function solve_sudoku(a){for(var d=[],e=[],b=0;9>b;b++)for(var c=0;9>c;c++){var h=a[b][c]-1;if(0<=h){var g=Array(324);g[9*b+c]=1;g[81+9*b+h]=1;g[162+9*c+h]=1;g[243+9*(3*Math.floor(b/3)+Math.floor(c/3))+h]=1;d.push(g);e.push({row:b,col:c,n:h+1})}else for(h=0;9>h;h++)g=Array(324),g[9*b+c]=1,g[81+9*b+h]=1,g[162+9*c+h]=1,g[243+9*(3*Math.floor(b/3)+Math.floor(c/3))+h]=1,d.push(g),e.push({row:b,col:c,n:h+1})}d=dlx_solve(d,0,2);if(0<d.length){c=d[0];for(b=0;b<c.length;b++)a[e[c[b]].row][e[c[b]].col]=e[c[b]].n;
return d.length}return 0}function solve(a){a=solve_sudoku(a);if(0<a){if(1<a)return 1}else return trace("no solution"),0}
function getBounds(a,d){var e={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){e.x2=-Infinity;e.y2=-Infinity;var b=a.children,c=b.length,h;for(h=0;h<c;h++){var g=getBounds(b[h],1);g.x<e.x&&(e.x=g.x);g.y<e.y&&(e.y=g.y);g.x+g.width>e.x2&&(e.x2=g.x+g.width);g.y+g.height>e.y2&&(e.y2=g.y+g.height)}Infinity==e.x&&(e.x=0);Infinity==e.y&&(e.y=0);Infinity==e.x2&&(e.x2=0);Infinity==e.y2&&(e.y2=0);e.width=e.x2-e.x;e.height=e.y2-e.y;delete e.x2;delete e.y2}else{if(a instanceof createjs.Bitmap){c=
a.sourceRect||a.image;h=c.width*d;var k=c.height*d}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){c=a.spriteSheet.getFrame(a.currentFrame);h=c.rect.width;k=c.rect.height;b=c.regX;var f=c.regY}else e.x=a.x||0,e.y=a.y||0;else e.x=a.x||0,e.y=a.y||0;b=b||0;h=h||0;f=f||0;k=k||0;e.regX=b;e.regY=f;c=a.localToGlobal(0-b,0-f);g=a.localToGlobal(h-b,k-f);h=a.localToGlobal(h-b,0-f);b=a.localToGlobal(0-b,k-f);e.x=
Math.min(Math.min(Math.min(c.x,g.x),h.x),b.x);e.y=Math.min(Math.min(Math.min(c.y,g.y),h.y),b.y);e.width=Math.max(Math.max(Math.max(c.x,g.x),h.x),b.x)-e.x;e.height=Math.max(Math.max(Math.max(c.y,g.y),h.y),b.y)-e.y}return e}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,e,b;0<d;)b=Math.floor(Math.random()*d),d--,e=a[d],a[d]=a[b],a[b]=e;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),e=0;e<d.length;e++){var b=d[e].split("=");if(b[0]==a)return b[1]}}function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},d,e,b,c,h,g;this.init=function(a,f,m){d={};b=e=0;c=a;h=f;g=m};this.addSprite=function(b,c){if(!a.hasOwnProperty(b)){var f=new Image;a[b]=d[b]={szPath:c,oSprite:f,bLoaded:!1};e++}};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e=0;h.call(g)};this._onSpriteLoaded=function(){c.call(g);++b===e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in d)d[a].oSprite.oSpriteLibrary=this,d[a].oSprite.szKey=
a,d[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},d[a].oSprite.onerror=function(a){var b=a.currentTarget;setTimeout(function(){d[b.szKey].oSprite.src=d[b.szKey].szPath},500)},d[a].oSprite.src=d[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1080,CANVAS_HEIGHT=1920,EDGEBOARD_X=25,EDGEBOARD_Y=200,CELL_SIZE=106,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="Arial",SECONDARY_FONT="blackplotan",PRIMARY_FONT_COLOUR="#008df0",TIME_LOOP_WAIT=2E3,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,EASY_MODE=0,MEDIUM_MODE=1,HARD_MODE=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,MAX_GIVENS_EASY,MAX_GIVENS_MEDIUM,MAX_GIVENS_HARD,RANGE_GIVENS=0,LOWER_BOUND_EASY=4,
LOWER_BOUND_MEDIUM=3,LOWER_BOUND_HARD=2,TIME_BONUS_LIMIT=[],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_PRELOADER_CONTINUE="START";TEXT_GAMEOVER="YOU COMPLETED ";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_SUDOKU=" SUDOKU";TEXT_IN=" IN ";TEXT_HELP_USED="YOU USED THE FOLLOWING HELP:";TEXT_HELPS_USED="YOU USED THE FOLLOWING HELPS:";TEXT_HELP_NOTE="NOTES AUTOFILL";TEXT_HELP_SOLVE="SOLVER";TEXT_HELP_TIME="SET NO TIME";TEXT_HELP_HINT=" HINT";TEXT_HELP_HINTS=" HINTS";TEXT_SCORE="SCORE:";TEXT_PLAY="PLAY";
TEXT_RESTART="RESTART";TEXT_TIME="TIME";TEXT_GENERATE_SUDOKU="GENERATING SUDOKU. PLEASE WAIT";TEXT_PAUSE="PAUSE";TEXT_DEVELOPED="DEVELOPED BY";TEXT_INFO_SOLVE="(all points lost)";TEXT_INFO_NOTE="(half of all points lost)";TEXT_INFO_HINT="points per hint)";TEXT_TOP_MODE="SELECT YOUR LEVEL";TEXT_EASY="BEGINNER";TEXT_MEDIUM="INTERMEDIATE";TEXT_HARD="ADVANCED";TEXT_HELP0="RULES";TEXT_HELP1="FILL IN THE BLANKS WITH NUMBERS FROM 1 TO 9. EACH ROW, COLUMN OR 3X3 BLOCK, MUST CONTAIN THE NUMBER 1 THROUGH 9 EXACTLY ONCE";
TEXT_HELP0_PAGE2="HOW-TO";TEXT_HELP1_PAGE2="USE KEYBOARD OR NUMBER BUTTONS TO FILL IN THE BLANKS. THERE ARE 3 DIFFERENT GAME MODES:";TEXT_HELP1_MOB_PAGE2="USE NUMBER BUTTONS TO FILL BLANKS IN GAME. THERE ARE 3 DIFFERENT GAME MODES:";TEXT_HELP2_PAGE2='"CELL FIRST" MODE: CLICK FIRST THE CELL YOU WANT TO FILL IN, THEN SELECT THE NUMBER YOU WANT TO ENTER';TEXT_HELP3_PAGE2='"NUMBER FIRST" MODE: SELECT THE NUMBER YOU WANT TO ENTER FIRST, THEN CLICK THE CELL YOU WANT TO FILL IN';TEXT_HELP4_PAGE2="MEMO MODE: THIS BUTTON ALLOWS YOU TO WRITE DOWN A MEMO IN A BLANK";
TEXT_FILL_WITH_NOTE="FILL THE BOARD WITH NOTES";TEXT_DELETE_ALL_NOTE="DELETE ALL NOTES";TEXT_SOLVE="SOLVE THE SUDOKU";TEXT_RESET="RESET THE SUDOKU";TEXT_SETNOTIME="PLAY WITHOUT TIME";TEXT_GETHINT="GET A HINT";TEXT_FULLSCREEN="FULL SCREEN";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,d,e,b,c,h,g,k,f,m;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();m=new createjs.Container;s_oStage.addChild(m)};this.unload=function(){m.removeAllChildren();f.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var r=new createjs.Shape;r.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.addChild(r);r=s_oSpriteLibrary.getSprite("200x200");g=createBitmap(r);g.regX=.5*r.width;g.regY=.5*r.height;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-180;m.addChild(g);k=new createjs.Shape;k.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(g.x-100,g.y-100,200,200,10);m.addChild(k);g.mask=k;
r=s_oSpriteLibrary.getSprite("progress_bar");b=createBitmap(r);b.x=CANVAS_WIDTH/2-r.width/2;b.y=CANVAS_HEIGHT/2+50;m.addChild(b);a=r.width;d=r.height;c=new createjs.Shape;c.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(b.x,b.y,1,d);m.addChild(c);b.mask=c;e=new createjs.Text("","30px "+PRIMARY_FONT,PRIMARY_FONT_COLOUR);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+100;e.textBaseline="alphabetic";e.textAlign="center";m.addChild(e);r=s_oSpriteLibrary.getSprite("but_start");f=new CTextButton(CANVAS_WIDTH/
2,CANVAS_HEIGHT/2,r,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 50",m);f.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);f.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);m.removeChild(h)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(f){e.text=f+"%";100===f&&(s_oMain._onRemovePreloader(),
e.visible=!1,b.visible=!1);c.graphics.clear();f=Math.floor(f*a/100);c.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(b.x,b.y,f,d)};this._init()}
function CMain(a){var d,e=0,b=0,c=STATE_LOADING,h,g;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages()};this.soundLoaded=function(){e++;h.refreshLoader(Math.floor(e/b*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"press_button",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"game_over",loop:!1,
volume:1,ingamename:"game_over"});b+=s_aSoundsInfo.length;s_aSounds=[];for(var a=0;a<s_aSoundsInfo.length;a++)this.tryToLoadSound(s_aSoundsInfo[a],!1)};this.tryToLoadSound=function(a,b){setTimeout(function(){s_aSounds[a.ingamename]=new Howl({src:[a.path+a.filename+".mp3"],autoplay:!1,preload:!0,loop:a.loop,volume:a.volume,onload:s_oMain.soundLoaded,onloaderror:function(a,b){for(var c=0;c<s_aSoundsInfo.length;c++)if(a===s_aSounds[s_aSoundsInfo[c].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[c],
!0);break}},onplayerror:function(a){for(var b=0;b<s_aSoundsInfo.length;b++)if(a===s_aSounds[s_aSoundsInfo[b].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[b].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[b].ingamename].play()});break}}})},b?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_credits",
"./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_mode_menu","./sprites/bg_mode_menu.jpg");s_oSpriteLibrary.addSprite("mod_easy_icon","./sprites/mod_easy_icon.png");s_oSpriteLibrary.addSprite("mod_medium_icon","./sprites/mod_medium_icon.png");s_oSpriteLibrary.addSprite("mod_hard_icon","./sprites/mod_hard_icon.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");
s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_help2","./sprites/bg_help2.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("config_icon","./sprites/config_icon.png");s_oSpriteLibrary.addSprite("but_help_icon","./sprites/but_help_icon.png");
s_oSpriteLibrary.addSprite("but_help_note","./sprites/but_help_note.png");s_oSpriteLibrary.addSprite("but_del_note","./sprites/but_del_note.png");s_oSpriteLibrary.addSprite("but_solve","./sprites/but_solve.png");s_oSpriteLibrary.addSprite("but_reset","./sprites/but_reset.png");s_oSpriteLibrary.addSprite("but_time","./sprites/but_time.png");s_oSpriteLibrary.addSprite("but_help_hint","./sprites/but_help_hint.png");s_oSpriteLibrary.addSprite("time_display","./sprites/time_display.png");s_oSpriteLibrary.addSprite("given_bg",
"./sprites/given_bg.png");s_oSpriteLibrary.addSprite("blank","./sprites/blank.png");s_oSpriteLibrary.addSprite("background","./sprites/background.png");s_oSpriteLibrary.addSprite("highlight","./sprites/highlight.png");s_oSpriteLibrary.addSprite("cell_selected","./sprites/cell_selected.png");s_oSpriteLibrary.addSprite("but_num","./sprites/but_num.png");s_oSpriteLibrary.addSprite("but_del_toggle","./sprites/but_del_toggle.png");s_oSpriteLibrary.addSprite("note_toggle","./sprites/note_toggle.png");s_oSpriteLibrary.addSprite("mode_toggle",
"./sprites/mode_toggle.png");s_oSpriteLibrary.addSprite("credit_bg","./sprites/credit_bg.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_fullscreen_help","./sprites/but_fullscreen_help.png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){e++;h.refreshLoader(Math.floor(e/b*100))};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=
function(){h.unload();this.gotoMenu()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.goToModeMenu=function(){new CModeMenu;c=STATE_MENU};this.gotoGame=function(a){s_iDifficultyMode=a;g=new CGame(k);c=STATE_GAME};this.gotoHelp=function(){new CHelp;c=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display",
"none");s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&g.update();s_oStage.update(a)}};s_oMain=this;var k=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}
var s_bMobile,s_iDifficultyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas,s_bFullscreen=!1,s_aSounds,s_aSoundsInfo;
function CTextButton(a,d,e,b,c,h,g,k){var f,m,r,q,t,p,v,n,D,y;this._init=function(a,b,c,d,e,g,h){f=!1;m=1;r=[];q=[];y=createBitmap(c);n=new createjs.Container;n.x=a;n.y=b;n.regX=c.width/2;n.regY=c.height/2;s_bMobile||(n.cursor="pointer");n.addChild(y,D);k.addChild(n);D=new CTLText(n,10,5,c.width-20,c.height-10,h,"center",g,e,1,0,0,d,!0,!0,!1,!1);this._initListener()};this.unload=function(){n.off("mousedown",t);n.off("pressup",p);k.removeChild(n)};this.setVisible=function(a){n.visible=a};this.setAlign=
function(a){D.textAlign=a};this.setTextX=function(a){D.x=a};this.setScale=function(a){m=n.scaleX=n.scaleY=a};this.enable=function(){f=!1};this.disable=function(){f=!0};this._initListener=function(){t=n.on("mousedown",this.buttonDown);p=n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){r[a]=b;q[a]=c};this.addEventListenerWithParams=function(a,b,c,d){r[a]=b;q[a]=c;v=d};this.buttonRelease=function(){f||(playSound("click",1,!1),n.scaleX=m,n.scaleY=m,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(q[ON_MOUSE_UP],
v))};this.buttonDown=function(){f||(n.scaleX=.9*m,n.scaleY=.9*m,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){n.x=a;n.y=b};this.tweenPosition=function(a,b,c,d,e,f,m){createjs.Tween.get(n).wait(d).to({x:a,y:b},c,e).call(function(){void 0!==f&&f.call(m)})};this.changeText=function(a){D.refreshText(a)};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};
this.getSprite=function(){return n};this.getScale=function(){return n.scaleX};this._init(a,d,e,b,c,h,g)}
function CToggle(a,d,e,b,c){var h,g,k,f,m,r,q;this._init=function(a,b,c,d){g=[];k=[];var e=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=d;f=createSprite(e,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);f.x=a;f.y=b;f.stop();t.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",m);f.off("pressup",r);s_bMobile||f.off("mouseover",q);t.removeChild(f)};this._initListener=
function(){m=f.on("mousedown",this.buttonDown);r=f.on("pressup",this.buttonRelease);s_bMobile||(q=f.on("mouseover",this.buttonOver))};this.addEventListener=function(a,b,c){g[a]=b;k[a]=c};this.setActive=function(a){h=a;f.gotoAndStop("state_"+h)};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;playSound("click",1,!1);h=!h;f.gotoAndStop("state_"+h);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h)};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};
this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){f.x=a;f.y=b};var t=c;this._init(a,d,e,b)}
function CDeleteButton(a,d,e,b){var c,h,g,k,f,m,r,q;this._init=function(a,b,d,e){h=!0;g=[];k=[];var n=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});c=e;f=createSprite(n,"state_"+c,d.width/2/2,d.height/2,d.width/2,d.height);f.x=a;f.y=b;f.stop();s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",m);f.off("pressup",r);s_bMobile||f.off("mouseover",q);s_oStage.removeChild(f)};
this.changeMode=function(){h=!h;c=!1;f.gotoAndStop("state_"+c)};this.reset=function(){c=!1;f.gotoAndStop("state_"+c)};this._initListener=function(){m=f.on("mousedown",this.buttonDown);r=f.on("pressup",this.buttonRelease);s_bMobile||(q=f.on("mouseover",this.buttonOver))};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.addEventListener=function(a,b,c){g[a]=b;k[a]=c};this.setActive=function(a){c=a;f.gotoAndStop("state_"+c)};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;
h?(s_oInterface.setAllBlackColor(),c=!0,f.gotoAndStop("state_"+c),s_oGame.setDeleteState()):s_oGame.deleteCell();g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],c)};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=function(a,b){f.x=a;f.y=b};this._init(a,d,e,b)}
function CGfxButton(a,d,e,b){var c,h,g,k,f,m,r,q,t;this._init=function(a,b,d,e){c=1;h=[];g=[];k=createBitmap(d);k.x=a;k.y=b;k.regX=d.width/2;k.regY=d.height/2;q=e;q.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",f);k.off("pressup",m);s_bMobile||k.off("mouseover",r);q.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){f=k.on("mousedown",this.buttonDown);m=k.on("pressup",this.buttonRelease);s_bMobile||(r=k.on("mouseover",this.buttonOver))};
this.addEventListener=function(a,b,c){h[a]=b;g[a]=c};this.buttonRelease=function(){t||(k.scaleX=c,k.scaleY=c);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){t||(k.scaleX=.9*c,k.scaleY=.9*c);playSound("click",1,!1);h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.pulseAnimation=function(){t=createjs.Tween.get(k,{loop:!0}).to({scaleX:1.1*c,scaleY:1.1*c},850,createjs.Ease.quadOut).to({scaleX:c,
scaleY:c},650,createjs.Ease.quadIn)};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,d,e,b);return this}
function CMenu(){var a,d,e,b,c,h,g,k,f,m,r,q,t=null,p=null;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);var v=s_oSpriteLibrary.getSprite("but_play");k=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-600,v,TEXT_PLAY,SECONDARY_FONT,"#ffffff",130,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v=s_oSpriteLibrary.getSprite("audio_icon"),c=CANVAS_WIDTH-v.height/2-10,h=v.height/2+10,m=new CToggle(c,
h,v,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);v=s_oSpriteLibrary.getSprite("but_credits");e=v.height/2+10;b=v.height/2+10;r=new CGfxButton(e,b,v,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onButCreditRelease,this);v=window.document;var n=v.documentElement;t=n.requestFullscreen||n.mozRequestFullScreen||n.webkitRequestFullScreen||n.msRequestFullscreen;p=v.exitFullscreen||v.mozCancelFullScreen||v.webkitExitFullscreen||v.msExitFullscreen;!1===ENABLE_FULLSCREEN&&
(t=!1);t&&screenfull.isEnabled&&(v=s_oSpriteLibrary.getSprite("but_fullscreen"),a=e+v.width/2+10,d=b,q=new CToggle(a,d,v,s_bFullscreen,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},1E3).call(function(){f.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){k.unload();k=null;if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)m.unload(),m=null;t&&screenfull.isEnabled&&q.unload();s_oStage.removeChild(g);s_oMenu=g=null};this.refreshButtonPos=function(f,n){r.setPosition(e+f,n+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(c-f,n+h);t&&screenfull.isEnabled&&q.setPosition(a+f,d+n)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.goToModeMenu()};this._onButCreditRelease=
function(){new CCreditsPanel};this.resetFullscreenBut=function(){t&&screenfull.isEnabled&&q.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?p.call(window.document):t.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CModeMenu(){var a,d,e,b,c,h,g,k;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_mode_menu"));s_oStage.addChild(a);new CTLText(s_oStage,CANVAS_WIDTH/2-500,220,1E3,100,100,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_TOP_MODE,!0,!0,!1,!1);var f=CANVAS_WIDTH/2;d=new createjs.Container;d.x=f;d.y=420;e=new createjs.Container;e.x=f;e.y=850;b=new createjs.Container;b.x=f;b.y=1280;new CTLText(d,-160,-40,320,50,50,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_EASY,
!0,!0,!1,!1);var r=s_oSpriteLibrary.getSprite("mod_easy_icon");c=new CGfxButton(f,580,r,s_oStage);c.addEventListener(ON_MOUSE_UP,this._selectEasy,this);new CTLText(e,-160,-40,320,50,50,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_MEDIUM,!0,!0,!1,!1);r=s_oSpriteLibrary.getSprite("mod_medium_icon");h=new CGfxButton(f,1010,r,s_oStage);h.addEventListener(ON_MOUSE_UP,this._selectMedium,this);new CTLText(b,-160,-40,320,50,50,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_HARD,!0,!0,!1,
!1);r=s_oSpriteLibrary.getSprite("mod_hard_icon");g=new CGfxButton(f,1440,r,s_oStage);g.addEventListener(ON_MOUSE_UP,this._selectHard,this);s_oStage.addChild(d,e,b);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},400).call(function(){k.visible=!1})};this._selectEasy=function(){f.unload();$(s_oMain).trigger("start_level",1);s_oMain.gotoGame(0)};this._selectMedium=function(){f.unload();$(s_oMain).trigger("start_level",
1);s_oMain.gotoGame(1)};this._selectHard=function(){f.unload();$(s_oMain).trigger("start_level",1);s_oMain.gotoGame(2)};this.unload=function(){s_oStage.removeAllChildren();a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};var f=this;this._init()}
function CGame(a){function d(a){a||(a=window.event);a.preventDefault();a=a.keyCode-48;10>a&&0<a?x.pressNumButton(a):-2===a?x.pressDelButton():58>a&&48<a&&x.pressNumButton(a-48)}function e(a){a.preventDefault();a=a.keyCode-48;10>a&&0<a?x.releaseNumButton(a):-2===a?x.releaseDelButton():58>a&&48<a&&x.releaseNumButton(a-48)}var b,c,h,g,k,f,m,r,q,t,p,v,n,D,y,E,F,x,C=null,z,R,K,J,N;this._init=function(){r=m=f=k=g=h=!1;D=n=q=t=p=0;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);
K=null;x=new CInterface;z=new CGrid;y=Array(81);this._generateValidGrid(y);y=this._convertToMatrix(y);E=[];for(a=0;9>a;a++){E[a]=[];for(var b=0;9>b;b++)E[a][b]=y[a][b]}R=new CSudokuLoader;c=!0;!1===s_bMobile&&(document.onkeydown=d,document.onkeyup=e)};this.getHint=function(){n++;for(var a=[],b=0;9>b;b++)for(var c=0;9>c;c++)0===y[b][c]&&a.push({row:b,col:c});if(1===a.length)this.gameOver();else if(0!==a.length){shuffle(a);b=a[0].row;c=a[0].col;var d=E[b][c];y[b][c]=d;z.setHintNumber(b,c,d);z.setActiveCell(a[0]);
z.updateNote(d);z.setActiveCell(a[0]);this._getEndCounterAndSetButCounter()}};this.setNoTime=function(){b=!1;x.setNoTime();r=!0};this.solveAndWrite=function(){for(var a=0;9>a;a++)for(var b=0;9>b;b++)z.isGiven(a,b)&&y[a][b]===E[a][b]||(z.setSolvedNumber(a,b,E[a][b]),y[a][b]=E[a][b]);this._setEndingStateWhenSolve();m=!0};this.resetGame=function(){for(var a=0;9>a;a++)for(var b=0;9>b;b++)z.isGiven(a,b)||(z.deleteResetNumber(a,b),y[a][b]=0);this._getEndCounterAndSetButCounter();z.turnOffAllCells();z.highlightCells()};
this.fillWithNote=function(){this.clearNoteFill();for(var a=z.getList(0),b=0;b<a.length;b++)for(var c=a[b],d=1;10>d;d++)!0!==z.checkCollision(d,c.row,c.col,!1)&&z.writeHelpNote(d,c.row,c.col);f=!0};this.deleteAllNote=function(){this.clearNoteFill()};this.clearNoteFill=function(){z.deleteAllNote()};this.setNoteState=function(){h=!h};this.setDigitState=function(){k=!k;g=!1;q=0};this.setDeleteState=function(){g=!0;q=0};this.setCurNum=function(a){g=!1;q=a};this.activeCell=function(a){k&&!g?(z.setActiveCell(a),
this.writeNum(q)):k&&g?(z.setActiveCell(a),z.deleteCell()):z.setActiveCell(a)};this.writeNum=function(a){if(h)z.writeNote(a);else{var b=z.getCurActiveCell().row,c=z.getCurActiveCell().col,d=z.getCurActiveCell().num;z.writeNum(a);x.updateCounterOnButton(a,z.getList(a).length);0!==d&&x.updateCounterOnButton(d,z.getList(d).length);y[b][c]=a}};this.deleteCell=function(){var a=z.getCurActiveCell().num,b=z.getCurActiveCell().row,c=z.getCurActiveCell().col;z.deleteCell();0!==a&&(x.updateCounterOnButton(a,
z.getList(a).length),y[b][c]=0)};this.showPausePanel=function(a){a?null===K&&(K=new CPausePanel):null!==K&&(K.unload(),K=null)};this.tryShowAd=function(){D++;D===AD_SHOW_COUNTER&&(D=0,$(s_oMain).trigger("show_interlevel_ad"))};this.restartGame=function(){this.unload();this._init()};this.unload=function(){x.unload();null!==C&&C.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oGame=null};this.onExit=function(){this.unload();s_oMain.gotoMenu()};this._onExitHelp=function(){b=
!0};this.checkEndGame=function(a){"add"===a?t++:t--;81===t&&this.gameOver()};this.gameOver=function(){var a=Math.floor((TIME_BONUS_LIMIT[s_iDifficultyMode]-p)/100);C=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"),f,m,r,n,a);C.show(p)};this.pauseTimer=function(a){b=!a};this.update=function(){if(c){R.update();for(var a=0;12>a;a++){for(var d=0;9>d;d++)for(var e=0;9>e;e++)y[d][e]=E[d][e];this._generateMask(s_iDifficultyMode);this._coverGrid(y);v=solve(y);if(1!==v){c=!1;R.unload();this._coverGrid(y);
this.setGrid(y);b=!0;s_oMain.startUpdate();break}}}b&&(p+=s_iTimeElaps,5999E3<p&&(p=5999E3),x.refreshTime(formatTime(p)))};this.setGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)z.setGiven(b,c,a[b][c]);this._getEndCounterAndSetButCounter()};this._getEndCounterAndSetButCounter=function(){t=0;for(var a=1;10>a;a++){var b=z.getList(a).length;t+=b;x.updateCounterOnButton(a,b)}};this._setEndingStateWhenSolve=function(){t=81;for(var a=1;10>a;a++)x.updateCounterOnButton(a,9);J=new createjs.Shape;
J.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(J);N=J.on("mousedown",this.buttonDownWhenSolve);s_bMobile||(N=J.on("mouseover",this.buttonOverWhenSolve))};this.buttonDownWhenSolve=function(){J.off("mousedown",N);s_bMobile||J.off("mouseover",N);M.gameOver()};this.buttonOverWhenSolve=function(a){s_bMobile||(a.target.cursor="pointer")};this._convertToMatrix=function(a){for(var b=0,c=[],d=0;81>d;d+=9)c[b]=[a[d],a[d+1],a[d+2],a[d+3],a[d+4],a[d+
5],a[d+6],a[d+7],a[d+8]],b++;return c};this._generateMask=function(a){F=[];for(var b=0;9>b;b++){F[b]=[];for(var c=0;9>c;c++)F[b][c]=0}b=MAX_GIVENS_EASY-RANGE_GIVENS;switch(a){case EASY_MODE:b=MAX_GIVENS_EASY-RANGE_GIVENS;var d=b+Math.ceil(Math.random()*RANGE_GIVENS);var e=LOWER_BOUND_EASY;break;case MEDIUM_MODE:b=MAX_GIVENS_MEDIUM-RANGE_GIVENS;d=b+Math.ceil(Math.random()*RANGE_GIVENS);e=LOWER_BOUND_MEDIUM;break;case HARD_MODE:b=MAX_GIVENS_HARD-RANGE_GIVENS,d=b+Math.ceil(Math.random()*RANGE_GIVENS),
e=LOWER_BOUND_HARD}var f=[];for(b=0;9>b;b++)b<e?f.push(1):f.push(0);a=[];for(b=0;9>b;b++)for(a[b]=0,shuffle(f),c=0;9>c;c++)1===f[c]&&(F[b][c]=1);var n=[];for(b=0;9>b;b++)for(n[b]=0,shuffle(f),c=0;9>c;c++)1===f[c]&&(F[c][b]=1);for(b=f=0;9>b;b++)for(c=0;9>c;c++)1===F[b][c]&&(a[b]++,n[c]++,f++);d=f-d;if(0>d)this._generateMask(s_iDifficultyMode);else if(0===d)return;f=[];for(b=0;9>b;b++)for(c=0;9>c;c++)1===F[b][c]&&f.push({row:b,col:c,weightRow:a[b],weightCol:n[c],weightTotal:a[b]+n[c]});f.sort(function(a,
b){return a.weightTotal<b.weightTotal?-1:a.weightTotal>b.weightTotal?1:0});for(c=0;c<d;){b=f.length-1;if(0>b)break;if(f[b].weightRow>e&&f[b].weightCol>e){F[f[b].row][f[b].col]=0;var m=f[b].row,g=f[b].col;a[m]--;n[g]--;for(b=0;b<f.length;b++)f[b].row===m&&(f[b].weightRow=a[m],f[b].weightTotal--),f[b].col===g&&(f[b].weightCol=n[g],f[b].weightTotal--);c++}f.pop()}};this._coverGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)0===F[b][c]&&(a[b][c]=0)};this.printGrid=function(a){for(var b="",c=
0;9>c;c++){for(var d=0;9>d;d++)if(b+=a[c][d]+" ",2===d||5===d)b+="| ";b+="\n";if(2===c||5===c)b+="---------------------\n"}trace(b)};this._generateValidGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)a[9*b+c]=(3*b+Math.floor(b/3)+c)%9+1;for(b=0;42>b;b++){var d=Math.ceil(9*Math.random());do var f=Math.ceil(9*Math.random());while(d===f);for(c=0;9>c;c++)for(var e=0;9>e;e++)a[9*c+e]===d?a[9*c+e]=f:a[9*c+e]===f&&(a[9*c+e]=d)}for(e=0;42>e;e++)for(d=Math.floor(3*Math.random()),f=Math.floor(3*Math.random()),
c=0;9>c;c++)b=a[9*c+(3*d+e%3)],a[9*c+(3*d+e%3)]=a[9*c+(3*f+e%3)],a[9*c+(3*f+e%3)]=b;for(d=0;42>d;d++)for(e=Math.floor(3*Math.random()),f=Math.floor(3*Math.random()),c=0;9>c;c++)b=a[9*c+(d%3*3+e)],a[9*c+(d%3*3+e)]=a[9*c+(d%3*3+f)],a[9*c+(d%3*3+f)]=b;for(d=0;42>d;d++)for(c=Math.floor(3*Math.random()),f=Math.floor(3*Math.random()),e=0;9>e;e++)b=a[9*(d%3*3+c)+e],a[9*(d%3*3+c)+e]=a[9*(d%3*3+f)+e],a[9*(d%3*3+f)+e]=b};s_oGame=this;MAX_GIVENS_EASY=a.max_givens_beginner;MAX_GIVENS_MEDIUM=a.max_givens_intermediate;
MAX_GIVENS_HARD=a.max_givens_advanced;TIME_BONUS_LIMIT[0]=a.bonus_time_beginner;TIME_BONUS_LIMIT[1]=a.bonus_time_intermediate;TIME_BONUS_LIMIT[2]=a.bonus_time_advanced;AD_SHOW_COUNTER=a.ad_show_counter;var M=this;this._init()}var s_oGame;
function CInterface(){var a,d,e,b,c,h,g,k,f,m,r,q,t,p,v,n,D,y,E,F;this._init=function(){f=[];for(var x=0;9>x;x++)f[x+1]=5<x?new CNumButton(97+177.5*(x-6),1650,x+1):new CNumButton(97+177.5*x,1500,x+1);x=s_oSpriteLibrary.getSprite("but_del_toggle");m=new CDeleteButton(629.5,1650,x,!1);m.changeMode();x=s_oSpriteLibrary.getSprite("note_toggle");r=new CToggle(807,1650,x,!0,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onNoteToggle,this);x=s_oSpriteLibrary.getSprite("mode_toggle");q=new CToggle(984.5,
1650,x,!0,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onModeToggle,this);var C;x=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-x.height/2-20;k=x.height/2+10;E=new CGfxButton(g,k,x,s_oStage);E.addEventListener(ON_MOUSE_UP,this._onExit,this);c=C=CANVAS_WIDTH-x.width/2-175;h=x.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)x=s_oSpriteLibrary.getSprite("audio_icon"),D=new CToggle(c,h,x,s_bAudioActive,s_oStage),D.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);C=CANVAS_WIDTH-
x.width/2-257;x=s_oSpriteLibrary.getSprite("config_icon");e=C;b=x.height/2+10;y=new CGfxButton(e,b,x,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onConf,this);C=CANVAS_WIDTH-x.width/2-490;x=s_oSpriteLibrary.getSprite("but_help_icon");a=C;d=x.height/2+10;t=new CGfxButton(a,d,x,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onHelpPress,this);x=s_oSpriteLibrary.getSprite("time_display");n=createBitmap(x);n.x=220;n.y=260;s_oStage.addChild(n);p=new CTLText(s_oStage,30,278,180,60,60,"right",PRIMARY_FONT_COLOUR,
PRIMARY_FONT,1.1,0,0,TEXT_TIME,!0,!0,!1,!1);v=new CTLText(s_oStage,245,278,150,60,60,"center","#fff",PRIMARY_FONT,1.1,0,0,"00:00",!0,!0,!1,!1);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)D.unload(),D=null;E.unload();for(var a=0;9>a;a++)f[a+1].unload();m.unload();r.unload();q.unload();t.unload();s_oInterface=F=null};this.refreshButtonPos=function(f,n){E.setPosition(g-f,n+k);y.setPosition(e-f,n+b);t.setPosition(a-f,n+d);!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||D.setPosition(c-f,n+h)};this.refreshTime=function(a){v.refreshText(a)};this._onConf=function(){F=new CConfigPanel};this.setNoTime=function(){s_oStage.removeChild(p.getText(),v.getText(),n)};this._onHelpPress=function(){new CHelpPanel;s_oGame.pauseTimer(!0)};this._onNoteToggle=function(){s_oGame.setNoteState()};this._onModeToggle=function(){for(var a=0;9>a;a++)f[a+1].changeMode();m.changeMode();this.setAllBlackColor();s_oGame.setDigitState()};this.updateCounterOnButton=function(a,b){f[a].clearCounter();
f[a].setCounter(b)};this.pressNumButton=function(a){f[a].buttonDown()};this.releaseNumButton=function(a){f[a].buttonRelease()};this.pressDelButton=function(){m.buttonDown()};this.releaseDelButton=function(a){m.buttonRelease()};this.setAllBlackColor=function(){for(var a=0;9>a;a++)f[a+1].changeNumColor(!1);m.reset()};this.resetFullscreenBut=function(){F&&F.resetFullscreenBut()};this.onExitFromConfig=function(){F=null};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
this._onExit=function(){new CAreYouSurePanel(s_oInterface._onConfirmExit)};this._onNegateExit=function(){};this._onConfirmExit=function(){$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,d,e,b,c,h,g,k,f,m,r;this._init=function(){var q=this;b=new createjs.Container;s_oStage.addChild(b);d=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));b.addChild(d);var p=CANVAS_WIDTH/2,v=CANVAS_HEIGHT/2-400;new CTLText(b,p-350,v-210,700,140,140,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_HELP0,!0,!0,!1,!1);new CTLText(b,p-400,v,800,250,48,"center",PRIMARY_FONT_COLOUR,PRIMARY_FONT,1,0,0,TEXT_HELP1,!0,!0,!0,!1);h=b.on("pressup",function(){q._onExitHelp()});
c=new createjs.Container;c.visible=0;s_oStage.addChild(c);c.on("pressup",function(){q._onExitHelp()});e=createBitmap(s_oSpriteLibrary.getSprite("bg_help2"));c.addChild(e);a=!1===s_bMobile?TEXT_HELP1_PAGE2:TEXT_HELP1_MOB_PAGE2;new CTLText(c,p-400,v-210,800,140,140,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_HELP0_PAGE2,!0,!0,!1,!1);new CTLText(c,CANVAS_WIDTH/2-400,CANVAS_HEIGHT/2-470,800,80,35,"center",PRIMARY_FONT_COLOUR,PRIMARY_FONT,1,0,0,a,!0,!0,!0,!1);new CTLText(c,CANVAS_WIDTH/2-200,
CANVAS_HEIGHT/2-300,600,150,35,"left",PRIMARY_FONT_COLOUR,PRIMARY_FONT,1,0,0,TEXT_HELP2_PAGE2,!0,!0,!0,!1);new CTLText(c,CANVAS_WIDTH/2-380,CANVAS_HEIGHT/2+10,600,150,35,"right",PRIMARY_FONT_COLOUR,PRIMARY_FONT,1,0,0,TEXT_HELP3_PAGE2,!0,!0,!0,!1);new CTLText(c,CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+300,600,150,35,"left",PRIMARY_FONT_COLOUR,PRIMARY_FONT,1,0,0,TEXT_HELP4_PAGE2,!0,!0,!0,!1);g=c.on("pressup",function(){q._onExitHelp()});createjs.Tween.get(c).to({alpha:1},700);m=createBitmap(s_oSpriteLibrary.getSprite("arrow"));
m.x=740;m.y=1450;m.alpha=0;k=m.on("click",q._changePageTo2);if(!s_bMobile)m.on("mouseover",q.buttonOver);s_oStage.addChild(m);r=createBitmap(s_oSpriteLibrary.getSprite("arrow"));r.scaleX=-1;r.x=340;r.y=1450;r.visible=!1;f=r.on("click",q._changePageTo1);if(!s_bMobile)r.on("mouseover",q.buttonOver);s_oStage.addChild(r);createjs.Tween.get(m).to({alpha:1},700)};this.unload=function(){s_oStage.removeChild(b,c,m,r);b.off("pressup",h);c.off("pressup",g);s_bMobile||(m.off("mouseover",k),r.off("mouseover",
f))};this._changePageTo1=function(){c.visible=!1;r.visible=!1;b.visible=!0;m.visible=!0};this._changePageTo2=function(){b.visible=!1;m.visible=!1;c.visible=!0;r.visible=!0};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this._onExitHelp=function(){$(s_oMain).trigger("show_interlevel_ad");q.unload();s_oGame._onExitHelp()};var q=this;this._init()}
function CPausePanel(){var a,d,e;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));e=new createjs.Text(TEXT_PAUSE," 120px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=700;d=new createjs.Container;d.addChild(a,e);s_oStage.addChild(d);s_oStage.update()};this.unload=function(){s_oStage.removeChild(d)};this._init()}
function CSudokuLoader(){var a,d,e,b,c;this._init=function(){a=!0;d=0;e=new createjs.Container;s_oStage.addChild(e);var h=(new createjs.Graphics).beginFill("rgba(0,0,0,0.8)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c=new createjs.Shape(h);c.on("click",function(){});e.addChild(c);new CTLText(e,.5*CANVAS_WIDTH-400,.5*CANVAS_HEIGHT-100,800,120,60,"center","#fff",SECONDARY_FONT,1,0,0,TEXT_GENERATE_SUDOKU,!0,!0,!0,!1);b=new createjs.Text(""," 180px "+PRIMARY_FONT,"#ffffff");b.x=.5*CANVAS_WIDTH-76;b.y=
.5*CANVAS_HEIGHT+50;b.textAlign="left";b.textBaseline="alphabetic";b.lineWidth=800;e.addChild(b)};this.unload=function(){a=!1;s_oStage.removeChild(e)};this.update=function(){a&&(d+=s_iTimeElaps,0<=d&&d<TIME_LOOP_WAIT/4?b.text="":d>=TIME_LOOP_WAIT/4&&d<2*TIME_LOOP_WAIT/4?b.text=".":d>=2*TIME_LOOP_WAIT/4&&d<3*TIME_LOOP_WAIT/4?b.text="..":d>=3*TIME_LOOP_WAIT/4&&d<TIME_LOOP_WAIT?b.text="...":d=0)};s_oSudokuLoader=this;this._init()}var s_oSudokuLoader;
function CEndPanel(a,d,e,b,c,h){var g,k,f,m,r,q,t,p,v;this._init=function(a,b,c,d,e,h){g=h;if(0<e){var n=Math.floor(TIME_BONUS_LIMIT[s_iDifficultyMode]/4E3);g-=n*e}b&&(g/=2);if(c||d)g=0;0>g&&(g=0);k=[];b&&k.push(TEXT_HELP_NOTE+" "+TEXT_INFO_NOTE);c&&k.push(TEXT_HELP_SOLVE+" "+TEXT_INFO_SOLVE);d&&k.push(TEXT_HELP_TIME+" "+TEXT_INFO_SOLVE);0<e&&(1<e?k.push(e+TEXT_HELP_HINTS+" (-"+n+" "+TEXT_INFO_HINT):k.push(e+TEXT_HELP_HINT+" (-"+n+" "+TEXT_INFO_HINT));r=new createjs.Container;r.alpha=0;r.visible=
!1;s_oStage.addChild(r);m=createBitmap(a);r.addChild(m);q=new CTLText(r,CANVAS_WIDTH/2-350,CANVAS_HEIGHT/2-562,700,300,80,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0," ",!0,!0,!0,!1);t=new CTLText(r,CANVAS_WIDTH/2-350,CANVAS_HEIGHT/2-220,700,80,50,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0," ",!0,!0,!0,!1);f=[];a=CANVAS_WIDTH/2-350;f[0]=new CTLText(r,a,CANVAS_HEIGHT/2-90,700,80,40,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0," ",!0,!0,!0,!1);f[1]=new CTLText(r,a,CANVAS_HEIGHT/2+
10,700,80,40,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0," ",!0,!0,!0,!1);f[2]=new CTLText(r,a,CANVAS_HEIGHT/2+110,700,80,40,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0," ",!0,!0,!0,!1);f[3]=new CTLText(r,a,CANVAS_HEIGHT/2+210,700,80,40,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0," ",!0,!0,!0,!1);p=new CTLText(r,a,CANVAS_HEIGHT/2+380,700,70,70,"center",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0," ",!0,!0,!1,!1)};this.unload=function(){r.off("mousedown",v)};this._initListener=function(){v=
r.on("mousedown",this._onExit)};this.show=function(a){playSound("game_over",1,!1);a=formatTime(a);var n=[];n[0]=TEXT_EASY;n[1]=TEXT_MEDIUM;n[2]=TEXT_EASY;b?q.refreshText(TEXT_GAMEOVER+n[s_iDifficultyMode]+TEXT_SUDOKU):q.refreshText(TEXT_GAMEOVER+n[s_iDifficultyMode]+TEXT_SUDOKU+TEXT_IN+a);1===k.length?t.refreshText(TEXT_HELP_USED):1<k.length&&t.refreshText(TEXT_HELPS_USED);if(0<k.length)for(n=0;n<k.length;n++)f[n].refreshText("-"+k[n]);p.refreshText(TEXT_SCORE+" "+g);r.visible=!0;var m=this;createjs.Tween.get(r).to({alpha:1},
500).call(function(){m._initListener()});$(s_oMain).trigger("save_score",[g,s_iDifficultyMode,a,d,e,b,c]);$(s_oMain).trigger("share_event",h);$(s_oMain).trigger("end_level",1)};this._onExit=function(){r.off("mousedown",v);s_oStage.removeChild(r);$(s_oMain).trigger("end_session");s_oGame.onExit()};this._init(a,d,e,b,c,h);return this}
function CConfigPanel(){var a=null,d=null,e,b,c,h,g,k,f,m,r,q,t,p,v,n,D,y,E;this._init=function(){s_oGame.pauseTimer(!0);var x=this;e=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));t=new createjs.Container;t.x=130;t.y=450;s_oStage.addChild(t);new CTLText(t,0,-50,600,50,50,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_GETHINT,!0,!0,!1,!1);var C=s_oSpriteLibrary.getSprite("but_help_hint");m=new CGfxButton(750,0,C,t);m.addEventListener(ON_MOUSE_UP,this._onHintPress,this);p=new createjs.Container;
p.x=130;p.y=620;s_oStage.addChild(p);new CTLText(p,0,-50,600,50,50,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_FILL_WITH_NOTE,!0,!0,!1,!1);C=s_oSpriteLibrary.getSprite("but_help_note");c=new CGfxButton(750,0,C,p);c.addEventListener(ON_MOUSE_UP,this._onHelpPress,this);v=new createjs.Container;v.x=130;v.y=790;s_oStage.addChild(v);new CTLText(v,0,-50,600,50,50,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_SOLVE,!0,!0,!1,!1);C=s_oSpriteLibrary.getSprite("but_solve");g=new CGfxButton(750,
0,C,v);g.addEventListener(ON_MOUSE_UP,this._onSolvePress,this);n=new createjs.Container;n.x=130;n.y=1210;s_oStage.addChild(n);new CTLText(n,0,-50,600,50,50,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_RESET,!0,!0,!1,!1);C=s_oSpriteLibrary.getSprite("but_reset");k=new CGfxButton(750,0,C,n);k.addEventListener(ON_MOUSE_UP,this._onResetPress,this);D=new createjs.Container;D.x=130;D.y=1390;s_oStage.addChild(D);new CTLText(D,0,-50,600,50,50,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_DELETE_ALL_NOTE,
!0,!0,!1,!1);C=s_oSpriteLibrary.getSprite("but_del_note");h=new CGfxButton(750,0,C,D);h.addEventListener(ON_MOUSE_UP,this._onDelPress,this);y=new createjs.Container;y.x=130;y.y=1570;s_oStage.addChild(y);new CTLText(y,0,-50,600,50,50,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_SETNOTIME,!0,!0,!1,!1);C=s_oSpriteLibrary.getSprite("but_time");f=new CGfxButton(750,0,C,y);f.addEventListener(ON_MOUSE_UP,this._onTimePress,this);C=window.document;var z=C.documentElement;a=z.requestFullscreen||z.mozRequestFullScreen||
z.webkitRequestFullScreen||z.msRequestFullscreen;d=C.exitFullscreen||C.mozCancelFullScreen||C.webkitExitFullscreen||C.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(a=!1);E=new createjs.Container;E.x=130;E.y=1030;s_oStage.addChild(E);a&&screenfull.isEnabled&&(new CTLText(E,0,-50,600,50,50,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_FULLSCREEN,!0,!0,!1,!1),C=s_oSpriteLibrary.getSprite("but_fullscreen"),r=new CToggle(750,0,C,s_bFullscreen,E),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,
this));b=new createjs.Container;b.addChild(e,t,p,v,n,D,y,E);s_oStage.addChild(b);q=e.on("pressup",function(){x._onExitHelp()})};this.unload=function(){$(s_oMain).trigger("show_interlevel_ad");s_oStage.removeChild(b);e.off("pressup",q);s_oInterface.onExitFromConfig()};this._onHelpPress=function(){s_oGame.fillWithNote();F._onExitHelp()};this._onDelPress=function(){s_oGame.deleteAllNote();F._onExitHelp()};this._onSolvePress=function(){s_oGame.solveAndWrite();F.unload()};this._onResetPress=function(){$(s_oMain).trigger("restart_level",
1);s_oGame.resetGame();F._onExitHelp()};this._onTimePress=function(){s_oGame.setNoTime();F._onExitHelp()};this._onHintPress=function(){s_oGame.getHint();F._onExitHelp()};this.resetFullscreenBut=function(){a&&screenfull.isEnabled&&r.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?d.call(window.document):a.call(window.document.documentElement);sizeHandler()};this._onExitHelp=function(){F.unload();s_oGame.pauseTimer(!1)};var F=this;this._init()}
function CGrid(){var a,d,e,b,c,h,g,k;this._init=function(){d=a=0;h=new createjs.Container;h.x=CANVAS_WIDTH/2;h.y=880;s_oStage.addChild(h);var f=CELL_SIZE,m=9*CELL_SIZE+44,r=.5*m,q=f,t=[];t.push(.5*f);g=[];for(var p=0;8>p;p++){if(2===p%3){var v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-r,-r+q,m,10);q+=f+10}else v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-r,-r+q,m,4),q+=f+4;t.push(q-.5*f);g[p]=new createjs.Shape(v);h.addChild(g[p])}q=f;k=[];for(p=0;8>p;p++)2===
p%3?(v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-r+q,-r,10,m),q+=f+10):(v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-r+q,-r,4,m),q+=f+4),k[p]=new createjs.Shape(v),h.addChild(k[p]);v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-r-10,-r-10,10,m+20);p=new createjs.Shape(v);h.addChild(p);v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(r,-r-10,10,m+20);p=new createjs.Shape(v);h.addChild(p);v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-r-
10,-r-10,m+20,10);p=new createjs.Shape(v);h.addChild(p);v=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-r-10,+r,m+20,10);m=new createjs.Shape(v);h.addChild(m);e=[];for(p=0;9>p;p++)for(e[p]=[],m=0;9>m;m++)e[p][m]={x:t[p],y:t[m]};b=[];for(p=0;9>p;p++)for(b[p]=[],m=0;9>m;m++)b[p][m]=new CCell(e[p][m].x-r,e[p][m].y-r,{row:p,col:m},h);c=[];for(p=0;10>p;p++)c[p]=[]};this.setCurNum=function(a){};this.setActiveCell=function(c){this.turnOffAllCells();a=c.row;d=c.col;this.highlightCells();0!==
b[a][d].getNumber()&&this.showSameNumbers(b[a][d].getNumber())};this.showCorner=function(){b[a][d].setCorner(!0)};this.turnOffAllCells=function(){for(var c=0;9>c;c++)for(var e=0;9>e;e++)b[c][e].highlight("off");b[a][d].setCorner(!1)};this.showSameNumbers=function(a){if(0!==a){for(var d=0;d<c[a].length;d++)b[c[a][d].row][c[a][d].col].highlight("green");for(d=0;9>d;d++)for(var e=0;9>e;e++)0!==b[d][e].getNote(a)&&b[d][e].highlight("green")}};this.highlightCells=function(){this.showCorner();for(var c=
0;9>c;c++)b[a][c].highlight("yellow");for(c=0;9>c;c++)b[c][d].highlight("yellow");c=3*Math.floor(a/3);for(var e=3*Math.floor(d/3),g=0;3>g;g++)for(var h=0;3>h;h++)b[c+g][e+h].highlight("yellow")};this.deleteCell=function(){b[a][d].getGiven()||(0!==b[a][d].getNumber()&&s_oGame.checkEndGame("remove"),this.deleteSmartFromList(b[a][d].getNumber()),b[a][d].clearCell(),this.turnOffAllCells(),this.highlightCells())};this.writeNum=function(c){b[a][d].getGiven()||0===c||c===b[a][d].getNumber()||(this.turnOffAllCells(),
this.highlightCells(),this.checkCollision(c,a,d,!0)||(0!==b[a][d].getNumber()&&this.deleteCell(),b[a][d].setNumber(c),this.insertSmartInList(c),this.updateNote(c),this.showSameNumbers(c),s_oGame.checkEndGame("add")))};this.deleteAllNote=function(){for(var e=0;e<c[0].length;e++)b[c[0][e].row][c[0][e].col].clearAllNote();this.turnOffAllCells();this.highlightCells();this.showSameNumbers(b[a][d].getNumber())};this.writeNote=function(c){b[a][d].getGiven()||(this.turnOffAllCells(),this.highlightCells(),
b[a][d].setNote(c),this.showSameNumbers(b[a][d].getNumber()))};this.writeHelpNote=function(a,c,d){b[c][d].setHelpNote(a)};this.setGiven=function(a,d,e){b[a][d].setGiven(e);c[e].push({row:a,col:d})};this.isGiven=function(a,c){return b[a][c].getGiven()};this.setSolvedNumber=function(a,d,e){b[a][d].setHintNumber(e);c[e].push({row:a,col:d});for(e=0;e<c[0].length;e++)c[0][e].row===a&&c[0][e].col===d&&c[0].splice(e,1)};this.setHintNumber=function(a,d,e){b[a][d].setHintNumber(e);c[e].push({row:a,col:d});
for(e=0;e<c[0].length;e++)c[0][e].row===a&&c[0][e].col===d&&c[0].splice(e,1)};this.deleteResetNumber=function(a,d){var e=b[a][d].getNumber();if(0!==e){for(var f=0;f<c[e].length;f++)c[e][f].row===a&&c[e][f].col===d&&c[e].splice(f,1);b[a][d].clearCell()}c[0].push({row:a,col:d})};this.updateNote=function(c){for(var e=0;9>e;e++)0!==b[a][e].getNote(c)&&b[a][e].clearNote(c),0!==b[e][d].getNote(c)&&b[e][d].clearNote(c);var f=3*Math.floor(a/3),g=3*Math.floor(d/3);for(e=0;3>e;e++)for(var h=0;3>h;h++)0!==b[f+
e][g+h].getNote(c)&&b[f+e][g+h].clearNote(c)};this.checkCollision=function(a,d,e,g){for(var f=3*Math.floor(d/3),h=3*Math.floor(e/3),k=0;k<c[a].length;k++)if(c[a][k].row===d||c[a][k].col===e||f<=c[a][k].row&&c[a][k].row<f+3&&h<=c[a][k].col&&c[a][k].col<h+3)return g&&b[c[a][k].row][c[a][k].col].highlight("red"),!0};this.deleteSmartFromList=function(b){if(0!==b){for(var e=0;e<c[b].length;e++)c[b][e].row===a&&c[b][e].col===d&&c[b].splice(e,1);c[0].push({row:a,col:d})}};this.insertSmartInList=function(b){if(0!==
b)for(c[b].push({row:a,col:d}),b=0;b<c[0].length;b++)c[0][b].row===a&&c[0][b].col===d&&c[0].splice(b,1)};this.removeList=function(a){c[a]={}};this.getList=function(a){return c[a]};this.viewList=function(a){trace(c[a]);trace(c[a].length)};this.getCurActiveCell=function(){return{row:a,col:d,num:b[a][d].getNumber()}};this.getCurGrid=function(){for(var a=[],c=0;9>c;c++){a[c]=[];for(var d=0;9>d;d++)a[c][d]=b[c][d].getNumber()}return a};this._init()}
function CCell(a,d,e,b){var c,h,g,k,f,m,r,q,t,p;this._init=function(a,b,d,e){c=!1;var n=CELL_SIZE;h=0;k=[];p=new createjs.Container;p.x=a;p.y=b;e.addChild(p);f={row:d.row,col:d.col};a=s_oSpriteLibrary.getSprite("background");b={images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{white:[0],grey:[1]}};b=new createjs.SpriteSheet(b);r=createSprite(b,"white",a.width/2/2,a.height/2,a.width/2,a.height);p.addChild(r);a=s_oSpriteLibrary.getSprite("highlight");b=
{images:[a],frames:{width:a.width/3,height:a.height,regX:a.width/3/2,regY:a.height/2},animations:{yellow:[0],green:[1],red:[2]}};b=new createjs.SpriteSheet(b);m=createSprite(b,"yellow",a.width/3/2,a.height/2,a.width/2,a.height);m.alpha=.9;m.visible=!1;p.addChild(m);g=[];a=n/3;g[1]={x:-a,y:-a};g[2]={x:0,y:-a};g[3]={x:a,y:-a};g[4]={x:-a,y:0};g[5]={x:0,y:0};g[6]={x:a,y:0};g[7]={x:-a,y:a};g[8]={x:0,y:a};g[9]={x:+a,y:a};this.clearAllNote();a=s_oSpriteLibrary.getSprite("cell_selected");q=createBitmap(a);
q.regX=a.width/2;q.regY=a.height/2;q.visible=!1;p.addChild(q);(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(-n/2,-n/2,n,n);p.on("click",this._setActive)};this.unload=function(){b.removeChild(p)};this.setGiven=function(a){0!==a&&(r.gotoAndStop("grey"),c=!0);this.setNumber(a)};this.getGiven=function(){return c};this.setHintNumber=function(a){0!==a&&(this.clearNumber(),this.clearAllNote(),t=new createjs.Text(a,"bold 80px "+PRIMARY_FONT,"#add8fd"),t.textAlign="center",t.textBaseline=
"middle",p.addChild(t),h=a)};this.setNumber=function(a){0!==a&&(this.clearNumber(),this.clearAllNote(),t=new createjs.Text(a,"bold 80px "+PRIMARY_FONT,"#000000"),t.textAlign="center",t.textBaseline="middle",p.addChild(t),h=a)};this.getNumber=function(){return h};this.clearNumber=function(){h=0;p.removeChild(t)};this.setNote=function(a){0===h&&(0!==k[a]?this.clearNote(a):(k[a]=new createjs.Text(a," 30px "+PRIMARY_FONT,"#000000"),k[a].textAlign="center",k[a].textBaseline="middle",k[a].x=g[a].x,k[a].y=
g[a].y,p.addChild(k[a])))};this.setHelpNote=function(a){this.clearNote(a);k[a]=new createjs.Text(a," 30px "+PRIMARY_FONT,"#000000");k[a].textAlign="center";k[a].textBaseline="middle";k[a].x=g[a].x;k[a].y=g[a].y;p.addChild(k[a])};this.getNote=function(a){return k[a]};this.clearNote=function(a){p.removeChild(k[a]);k[a]=0};this.clearAllNote=function(){for(var a=1;10>a;a++)p.removeChild(k[a]),k[a]=0};this.clearCell=function(){this.clearNumber();this.clearAllNote()};this.highlight=function(a){m.visible=
!0;"off"!==a?m.gotoAndStop(a):m.visible=!1};this.setCorner=function(a){q.visible=a?!0:!1};this._setActive=function(){v.highlight("yellow");s_oGame.activeCell(f)};var v=this;this._init(a,d,e,b)}
function CNumButton(a,d,e){var b,c,h,g,k,f,m,r,q,t,p;this._init=function(a,d,e){h=!1;g=e;m=new createjs.Container;m.x=a;m.y=d;s_oStage.addChild(m);d=s_oSpriteLibrary.getSprite("but_num");k=createBitmap(d);a=d.width;d=d.height;k.regX=a/2;k.regY=d/2;f=new createjs.Text(e,"Bold 90px "+PRIMARY_FONT,"#000000");f.textAlign="center";f.textBaseline="middle";m.addChild(k,f);b=a/3-2;c=-d/3+5;this.setCounter(0);this._initListener()};this.unload=function(){m.off("mousedown",q);m.off("pressup",t);s_bMobile||m.off("mouseover",
p);s_oStage.removeChild(m)};this._initListener=function(){q=m.on("mousedown",this.buttonDown);t=m.on("pressup",this.buttonRelease);s_bMobile||(p=m.on("mouseover",this.buttonOver))};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;s_oGame.tryShowAd();h?(s_oGame.setCurNum(g),s_oInterface.setAllBlackColor(),v.changeNumColor(!0)):s_oGame.writeNum(g)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.changeNumColor=function(a){f.color=
a?"#ff8814":"#000000"};this.changeMode=function(){h=!h};this.setCounter=function(a){r=new createjs.Text(a," 30px "+PRIMARY_FONT,"#000000");r.textAlign="center";r.textBaseline="middle";r.x=b;r.y=c;m.addChild(r)};this.clearCounter=function(){m.removeChild(r)};var v=this;this._init(a,d,e)}
function CCreditsPanel(){var a,d,e,b,c;this._init=function(){b=new createjs.Shape;b.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=.01;c=b.on("click",this._onLogoButRelease);s_oStage.addChild(b);a=new createjs.Container;s_oStage.addChild(a);var h=s_oSpriteLibrary.getSprite("credit_bg"),g=createBitmap(h);g.regX=h.width/2;g.regY=h.height/2;a.addChild(g);a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;h=new createjs.Text(TEXT_DEVELOPED," 80px "+SECONDARY_FONT,"#000000");h.y=-120;
h.textAlign="center";h.textBaseline="middle";h.lineWidth=600;h.outline=5;g=new createjs.Text(TEXT_DEVELOPED," 80px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);g.y=h.y;g.textAlign="center";g.textBaseline="middle";g.lineWidth=600;a.addChild(g);h=new createjs.Text("www.codethislab.com"," 80px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);h.y=120;h.textAlign="center";h.textBaseline="middle";h.lineWidth=600;h.outline=5;g=new createjs.Text("www.codethislab.com"," 80px "+SECONDARY_FONT,PRIMARY_FONT_COLOUR);g.y=h.y;g.textAlign=
"center";g.textBaseline="middle";g.lineWidth=600;a.addChild(g);h=s_oSpriteLibrary.getSprite("ctl_logo");e=createBitmap(h);e.regX=h.width/2;e.regY=h.height/2;a.addChild(e);h=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(400,-204,h,a);d.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){s_oStage.removeChild(void 0);s_oStage.removeChild(a);d.unload();b.off("click",c)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CAreYouSurePanel(a,d){var e,b,c,h;this._init=function(a,d){c=new createjs.Container;h=c.on("mousedown",function(){});s_oStage.addChild(c);var f=s_oSpriteLibrary.getSprite("credit_bg"),g=createBitmap(f);g.regX=f.width/2;g.regY=f.height/2;c.addChild(g);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;new CTLText(c,-400,-180,800,240,120,"left",PRIMARY_FONT_COLOUR,SECONDARY_FONT,1,0,0,TEXT_ARE_SURE,!0,!0,!0,!1);e=new CGfxButton(150,150,s_oSpriteLibrary.getSprite("but_yes"),c);e.addEventListener(ON_MOUSE_UP,
this._onButYes,this);b=new CGfxButton(-150,150,s_oSpriteLibrary.getSprite("but_exit"),c);b.addEventListener(ON_MOUSE_UP,this._onButNo,this);b.pulseAnimation()};this._onButYes=function(){g.unload();a&&a()};this._onButNo=function(){g.unload();d&&d()};this.unload=function(){b.unload();e.unload();c.off("mousedown",h);s_oStage.removeChild(c)};var g=this;this._init(a,d)}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,d,e,b){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,d,e,b))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,d,e,b,c,h,g,k,f,m,r,q,t,p,v,n,D){this._oContainer=a;this._x=d;this._y=e;this._iWidth=b;this._iHeight=c;this._bMultiline=n;this._iFontSize=h;this._szAlign=g;this._szColor=k;this._szFont=f;this._iPaddingH=r;this._iPaddingV=q;this._bVerticalAlign=v;this._bFitText=p;this._bDebug=D;this._oDebugShape=null;this._fLineHeightFactor=m;this._oText=null;t&&this.__createText(t)};